name: Reporting POC

on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call: {}

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout changes-reporting-poc with tags
        uses: actions/checkout@v4
        with:
          repository: khandramai/changes-reporting-poc
          ref: main
          fetch-depth: 0
          token: ${{ secrets.REPORTING_READ_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Ensure tags
        run: git fetch --tags --force

      - name: Determine current & previous tags
        id: tags
        shell: bash
        run: |
          mapfile -t TAGS < <(git for-each-ref --sort=-creatordate --format '%(refname:short)' refs/tags | head -n 2)
          if [ "${#TAGS[@]}" -lt 2 ]; then
            echo "Not enough tags to compare (need ≥2)." >&2
            exit 1
          fi
          echo "current=${TAGS[0]}" >> "$GITHUB_OUTPUT"
          echo "previous=${TAGS[1]}" >> "$GITHUB_OUTPUT"

      - name: Build report
        id: report
        env:
          CUR: ${{ steps.tags.outputs.current }}
          PREV: ${{ steps.tags.outputs.previous }}
        shell: bash
        run: |
          FILE="changes-${PREV}-to-${CUR}.md"
          {
            echo "# Changes between \`$PREV\` → \`$CUR\`"
            echo
            echo "## Commits"
            git log --oneline "${PREV}..${CUR}" || true
            echo
            echo "## Files changed (stats)"
            git diff --stat "${PREV}..${CUR}" || true
          } > "$FILE"
          cat "$FILE" >> "$GITHUB_STEP_SUMMARY"
          echo "file=${FILE}" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.report.outputs.file }}
          path: ${{ steps.report.outputs.file }}