name: Reporting POC

on:
  workflow_dispatch:
    inputs:
      from:
        description: "Start tag (optional)"
        required: false
        type: string
      to:
        description: "End tag (optional)"
        required: false
        type: string
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_call:
    inputs:
      from:
        required: false
        type: string
      to:
        required: false
        type: string

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout changes-reporting-poc with tags
        uses: actions/checkout@v4
        with:
          repository: khandramai/changes-reporting-poc
          ref: main
          fetch-depth: 0
          token: ${{ secrets.REPORTING_READ_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Ensure tags
        run: git fetch --tags --force

      - name: Determine range
        id: range
        shell: bash
        run: |
          FROM="${{ inputs.from }}"
          TO="${{ inputs.to }}"

          if [ -z "$FROM" ] || [ -z "$TO" ]; then
            mapfile -t TAGS < <(git for-each-ref --sort=-creatordate --format '%(refname:short)' refs/tags | head -n 2)
            if [ "${#TAGS[@]}" -lt 2 ]; then
              echo "Not enough tags to compare (need ≥2)." >&2
              exit 1
            fi
            TO="${TAGS[0]}"
            FROM="${TAGS[1]}"
          fi

          echo "from=$FROM" >> "$GITHUB_OUTPUT"
          echo "to=$TO" >> "$GITHUB_OUTPUT"

      - name: Build report
        id: report
        env:
          CUR: ${{ steps.range.outputs.to }}
          PREV: ${{ steps.range.outputs.from }}
        shell: bash
        run: |
          FILE="changes-${PREV}-to-${CUR}.md"
          {
            echo "# Changes between \`$PREV\` → \`$CUR\`"
            echo
            echo "## Commits"
            git log --oneline "${PREV}..${CUR}" || true
            echo
            echo "## Files changed (stats)"
            git diff --stat "${PREV}..${CUR}" || true
          } > "$FILE"
          cat "$FILE" >> "$GITHUB_STEP_SUMMARY"
          echo "file=${FILE}" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.report.outputs.file }}
          path: ${{ steps.report.outputs.file }}